#!/usr/bin/env python3
"""Tk control panel for Magic Mouse Linux Gestures."""

from __future__ import annotations

import subprocess
import tkinter as tk
from pathlib import Path
from tkinter import messagebox, ttk

from magic_mouse_daemon import load_env

APP_NAME = "Magic Mouse Control Panel"
SERVICE_NAME = "magic-mouse-gestures.service"
CONFIG_DIR = Path.home() / ".config" / "magic-mouse-gestures"
CONFIG_PATH = CONFIG_DIR / "profile.env"
PROJECT_DIR = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = PROJECT_DIR / "profiles"

PROFILE_ORDER = ["cosmic", "gnome-ubuntu"]
FIELD_ORDER = [
    "PROFILE_NAME",
    "GESTURE_LEFT",
    "GESTURE_RIGHT",
    "GESTURE_UP",
    "GESTURE_DOWN",
    "GESTURE_OVERVIEW",
    "MIN_TOUCHES",
    "SWIPE_THRESHOLD_X",
    "SWIPE_THRESHOLD_Y",
    "MAX_GESTURE_TIME_MS",
    "SWIPE_COOLDOWN_MS",
    "AXIS_LOCK_RATIO",
    "INVERT_X",
    "INVERT_Y",
    "SINGLE_FINGER_INVERT_X",
    "SINGLE_FINGER_INVERT_Y",
    "TWO_FINGER_INVERT_X",
    "TWO_FINGER_INVERT_Y",
    "COMMAND_TIMEOUT_SEC",
    "WAIT_RELEASE_AFTER_FIRE",
    "BACKEND",
    "HID_PATH",
]


def load_profile_defaults(name: str) -> dict[str, str]:
    path = TEMPLATE_DIR / f"{name}.env"
    values = load_env(path)
    values.setdefault("BACKEND", "auto")
    values.setdefault("HID_PATH", "")
    return values


def read_current_profile() -> dict[str, str]:
    if CONFIG_PATH.exists():
        values = load_env(CONFIG_PATH)
        values.setdefault("BACKEND", "auto")
        values.setdefault("HID_PATH", "")
        profile_name = values.get("PROFILE_NAME", "cosmic")
        defaults = load_profile_defaults(profile_name if profile_name in PROFILE_ORDER else "cosmic")
        merged = defaults | values
        merged.setdefault("PROFILE_NAME", profile_name)
        return merged
    return load_profile_defaults("cosmic")


def write_profile(values: dict[str, str]) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        f'# Generated by {APP_NAME}',
        '# Edit manually if needed: ~/.config/magic-mouse-gestures/profile.env',
        '',
    ]
    for key in FIELD_ORDER:
        value = values.get(key, "")
        if key == "HID_PATH" and not value:
            continue
        if key == "BACKEND" and not value:
            value = "auto"
        if key.startswith("GESTURE_") or key == "PROFILE_NAME":
            escaped = str(value).replace('"', '\\"')
            lines.append(f'{key}="{escaped}"')
        else:
            lines.append(f"{key}={value}")
    CONFIG_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


class ControlPanel(ttk.Frame):
    def __init__(self, master: tk.Tk):
        super().__init__(master, padding=14)
        self.master = master
        self.pack(fill="both", expand=True)

        self.vars: dict[str, tk.Variable] = {}
        self.status_var = tk.StringVar(value="Ready")
        self.service_var = tk.StringVar(value="Service: unknown")

        self._build_ui()
        self.load_into_form(read_current_profile())
        self.refresh_service_status()

    def _build_ui(self) -> None:
        self.master.title(APP_NAME)
        self.master.minsize(860, 620)

        header = ttk.Frame(self)
        header.pack(fill="x", pady=(0, 10))
        ttk.Label(header, text=APP_NAME, font=("TkDefaultFont", 14, "bold")).pack(anchor="w")
        ttk.Label(
            header,
            text="Configure gesture commands, sensitivity, and inversion settings.",
        ).pack(anchor="w")

        toolbar = ttk.Frame(self)
        toolbar.pack(fill="x", pady=(0, 10))
        for label, cmd in [
            ("Load", self.on_load),
            ("Save", self.on_save),
            ("Save + Restart Service", self.on_save_restart),
            ("Refresh Status", self.refresh_service_status),
        ]:
            ttk.Button(toolbar, text=label, command=cmd).pack(side="left", padx=(0, 8))

        notebook = ttk.Notebook(self)
        notebook.pack(fill="both", expand=True)

        general = ttk.Frame(notebook, padding=12)
        commands = ttk.Frame(notebook, padding=12)
        tuning = ttk.Frame(notebook, padding=12)
        service = ttk.Frame(notebook, padding=12)
        notebook.add(general, text="General")
        notebook.add(commands, text="Commands")
        notebook.add(tuning, text="Tuning")
        notebook.add(service, text="Service")

        self._build_general_tab(general)
        self._build_commands_tab(commands)
        self._build_tuning_tab(tuning)
        self._build_service_tab(service)

        status = ttk.Frame(self)
        status.pack(fill="x", pady=(10, 0))
        ttk.Label(status, textvariable=self.service_var).pack(anchor="w")
        ttk.Label(status, textvariable=self.status_var).pack(anchor="w")

    def _build_general_tab(self, parent: ttk.Frame) -> None:
        frame = ttk.Frame(parent)
        frame.pack(fill="both", expand=True)
        frame.columnconfigure(1, weight=1)

        self.vars["PROFILE_NAME"] = tk.StringVar()
        self.vars["MIN_TOUCHES"] = tk.StringVar()
        self.vars["BACKEND"] = tk.StringVar()
        self.vars["HID_PATH"] = tk.StringVar()
        self.vars["WAIT_RELEASE_AFTER_FIRE"] = tk.IntVar()
        self.vars["COMMAND_TIMEOUT_SEC"] = tk.StringVar()

        ttk.Label(frame, text="Desktop profile").grid(row=0, column=0, sticky="w", padx=(0, 10), pady=6)
        combo = ttk.Combobox(frame, textvariable=self.vars["PROFILE_NAME"], values=PROFILE_ORDER, state="readonly")
        combo.grid(row=0, column=1, sticky="ew", pady=6)
        combo.bind("<<ComboboxSelected>>", lambda _e: self.on_profile_changed())

        ttk.Label(frame, text="Minimum touches").grid(row=1, column=0, sticky="w", padx=(0, 10), pady=6)
        ttk.Spinbox(frame, from_=1, to=5, textvariable=self.vars["MIN_TOUCHES"], width=8).grid(row=1, column=1, sticky="w", pady=6)

        ttk.Label(frame, text="Backend").grid(row=2, column=0, sticky="w", padx=(0, 10), pady=6)
        ttk.Combobox(frame, textvariable=self.vars["BACKEND"], values=["auto", "hidraw", "hidapi"], state="readonly").grid(row=2, column=1, sticky="w", pady=6)

        ttk.Label(frame, text="Pinned HID path").grid(row=3, column=0, sticky="w", padx=(0, 10), pady=6)
        ttk.Entry(frame, textvariable=self.vars["HID_PATH"]).grid(row=3, column=1, sticky="ew", pady=6)

        ttk.Checkbutton(
            frame,
            text="Wait until all fingers lift after a gesture fires",
            variable=self.vars["WAIT_RELEASE_AFTER_FIRE"],
        ).grid(row=4, column=0, columnspan=2, sticky="w", pady=6)

        ttk.Label(frame, text="Command timeout (seconds)").grid(row=5, column=0, sticky="w", padx=(0, 10), pady=6)
        ttk.Entry(frame, textvariable=self.vars["COMMAND_TIMEOUT_SEC"], width=10).grid(row=5, column=1, sticky="w", pady=6)

        note = (
            "Tip: set Minimum touches to 1 if you want single-finger swipes to trigger gestures. "
            "The per-finger inversion options in the Tuning tab apply automatically based on how the gesture started."
        )
        ttk.Label(frame, text=note, wraplength=760, justify="left").grid(row=6, column=0, columnspan=2, sticky="w", pady=(18, 0))

    def _build_commands_tab(self, parent: ttk.Frame) -> None:
        frame = ttk.Frame(parent)
        frame.pack(fill="both", expand=True)
        frame.columnconfigure(1, weight=1)

        for key in ["GESTURE_LEFT", "GESTURE_RIGHT", "GESTURE_UP", "GESTURE_DOWN", "GESTURE_OVERVIEW"]:
            self.vars[key] = tk.StringVar()

        rows = [
            ("GESTURE_LEFT", "Swipe left"),
            ("GESTURE_RIGHT", "Swipe right"),
            ("GESTURE_UP", "Swipe up"),
            ("GESTURE_DOWN", "Swipe down"),
            ("GESTURE_OVERVIEW", "Overview"),
        ]
        for idx, (key, label) in enumerate(rows):
            ttk.Label(frame, text=label).grid(row=idx, column=0, sticky="nw", padx=(0, 10), pady=6)
            ttk.Entry(frame, textvariable=self.vars[key]).grid(row=idx, column=1, sticky="ew", pady=6)

        ttk.Label(
            frame,
            text="These commands are executed when the gesture is detected. Keep them as simple shell commands.",
            wraplength=760,
            justify="left",
        ).grid(row=len(rows), column=0, columnspan=2, sticky="w", pady=(18, 0))

    def _build_tuning_tab(self, parent: ttk.Frame) -> None:
        parent.columnconfigure(0, weight=1)
        parent.columnconfigure(1, weight=1)

        for key in [
            "SWIPE_THRESHOLD_X",
            "SWIPE_THRESHOLD_Y",
            "MAX_GESTURE_TIME_MS",
            "SWIPE_COOLDOWN_MS",
            "AXIS_LOCK_RATIO",
            "INVERT_X",
            "INVERT_Y",
            "SINGLE_FINGER_INVERT_X",
            "SINGLE_FINGER_INVERT_Y",
            "TWO_FINGER_INVERT_X",
            "TWO_FINGER_INVERT_Y",
        ]:
            self.vars[key] = tk.IntVar() if "INVERT" in key else tk.StringVar()

        basics = ttk.LabelFrame(parent, text="Detection", padding=12)
        basics.grid(row=0, column=0, sticky="nsew", padx=(0, 8), pady=(0, 8))
        basics.columnconfigure(1, weight=1)
        for idx, (key, label) in enumerate([
            ("SWIPE_THRESHOLD_X", "Horizontal threshold"),
            ("SWIPE_THRESHOLD_Y", "Vertical threshold"),
            ("MAX_GESTURE_TIME_MS", "Max gesture time (ms)"),
            ("SWIPE_COOLDOWN_MS", "Cooldown (ms)"),
            ("AXIS_LOCK_RATIO", "Axis lock ratio"),
        ]):
            ttk.Label(basics, text=label).grid(row=idx, column=0, sticky="w", padx=(0, 10), pady=6)
            ttk.Entry(basics, textvariable=self.vars[key]).grid(row=idx, column=1, sticky="ew", pady=6)

        legacy = ttk.LabelFrame(parent, text="Legacy global inversion", padding=12)
        legacy.grid(row=0, column=1, sticky="nsew", padx=(8, 0), pady=(0, 8))
        ttk.Checkbutton(legacy, text="Invert X globally", variable=self.vars["INVERT_X"]).pack(anchor="w", pady=4)
        ttk.Checkbutton(legacy, text="Invert Y globally", variable=self.vars["INVERT_Y"]).pack(anchor="w", pady=4)
        ttk.Label(
            legacy,
            text="These legacy switches remain for compatibility. The per-finger options below override them for new configs.",
            wraplength=320,
            justify="left",
        ).pack(anchor="w", pady=(10, 0))

        single = ttk.LabelFrame(parent, text="Single-finger inversion", padding=12)
        single.grid(row=1, column=0, sticky="nsew", padx=(0, 8), pady=(8, 0))
        ttk.Checkbutton(single, text="Invert X for single-finger gestures", variable=self.vars["SINGLE_FINGER_INVERT_X"]).pack(anchor="w", pady=4)
        ttk.Checkbutton(single, text="Invert Y for single-finger gestures", variable=self.vars["SINGLE_FINGER_INVERT_Y"]).pack(anchor="w", pady=4)

        double = ttk.LabelFrame(parent, text="Two-finger inversion", padding=12)
        double.grid(row=1, column=1, sticky="nsew", padx=(8, 0), pady=(8, 0))
        ttk.Checkbutton(double, text="Invert X for two-finger gestures", variable=self.vars["TWO_FINGER_INVERT_X"]).pack(anchor="w", pady=4)
        ttk.Checkbutton(double, text="Invert Y for two-finger gestures", variable=self.vars["TWO_FINGER_INVERT_Y"]).pack(anchor="w", pady=4)

    def _build_service_tab(self, parent: ttk.Frame) -> None:
        top = ttk.Frame(parent)
        top.pack(fill="x", pady=(0, 12))
        for label, cmd in [
            ("Start", lambda: self.run_service_command("start")),
            ("Stop", lambda: self.run_service_command("stop")),
            ("Restart", lambda: self.run_service_command("restart")),
            ("Enable", lambda: self.run_service_command("enable")),
            ("Disable", lambda: self.run_service_command("disable")),
        ]:
            ttk.Button(top, text=label, command=cmd).pack(side="left", padx=(0, 8))

        test = ttk.LabelFrame(parent, text="Test configured gestures", padding=12)
        test.pack(fill="x", pady=(0, 12))
        for label, gesture in [
            ("Test Left", "left"),
            ("Test Right", "right"),
            ("Test Up", "up"),
            ("Test Down", "down"),
            ("Test Overview", "overview"),
        ]:
            ttk.Button(test, text=label, command=lambda g=gesture: self.simulate_gesture(g)).pack(side="left", padx=(0, 8), pady=4)

        info = ttk.LabelFrame(parent, text="Installed paths", padding=12)
        info.pack(fill="both", expand=True)
        lines = [
            f"Profile file: {CONFIG_PATH}",
            f"Project directory: {PROJECT_DIR}",
            "Service: magic-mouse-gestures.service",
        ]
        for line in lines:
            ttk.Label(info, text=line, wraplength=760, justify="left").pack(anchor="w", pady=2)

    def _set_status(self, text: str) -> None:
        self.status_var.set(text)

    def on_profile_changed(self) -> None:
        selected = str(self.vars["PROFILE_NAME"].get())
        if selected not in PROFILE_ORDER:
            return
        defaults = load_profile_defaults(selected)
        current = self.collect_values()
        merged = defaults | {k: v for k, v in current.items() if k in {"MIN_TOUCHES", "BACKEND", "HID_PATH", "WAIT_RELEASE_AFTER_FIRE", "COMMAND_TIMEOUT_SEC"}}
        merged["PROFILE_NAME"] = selected
        self.load_into_form(merged)
        self._set_status(f"Loaded {selected} defaults into the form")

    def collect_values(self) -> dict[str, str]:
        values: dict[str, str] = {}
        for key, var in self.vars.items():
            values[key] = str(var.get()).strip()
        return values

    def load_into_form(self, values: dict[str, str]) -> None:
        for key, var in self.vars.items():
            value = values.get(key, "")
            if isinstance(var, tk.IntVar):
                try:
                    var.set(int(value or 0))
                except ValueError:
                    var.set(0)
            else:
                var.set(value)

    def on_load(self) -> None:
        self.load_into_form(read_current_profile())
        self.refresh_service_status()
        self._set_status(f"Loaded {CONFIG_PATH}")

    def validate(self, values: dict[str, str]) -> tuple[bool, str]:
        required_ints = [
            "MIN_TOUCHES",
            "SWIPE_THRESHOLD_X",
            "SWIPE_THRESHOLD_Y",
            "MAX_GESTURE_TIME_MS",
            "SWIPE_COOLDOWN_MS",
            "WAIT_RELEASE_AFTER_FIRE",
            "INVERT_X",
            "INVERT_Y",
            "SINGLE_FINGER_INVERT_X",
            "SINGLE_FINGER_INVERT_Y",
            "TWO_FINGER_INVERT_X",
            "TWO_FINGER_INVERT_Y",
        ]
        for key in required_ints:
            try:
                int(values.get(key, "0"))
            except ValueError:
                return False, f"{key} must be an integer"
        try:
            float(values.get("AXIS_LOCK_RATIO", "1.15"))
        except ValueError:
            return False, "AXIS_LOCK_RATIO must be a number"
        try:
            float(values.get("COMMAND_TIMEOUT_SEC", "2.0"))
        except ValueError:
            return False, "COMMAND_TIMEOUT_SEC must be a number"
        if values.get("PROFILE_NAME") not in PROFILE_ORDER:
            return False, "PROFILE_NAME must be cosmic or gnome-ubuntu"
        return True, ""

    def on_save(self) -> None:
        values = self.collect_values()
        ok, error = self.validate(values)
        if not ok:
            messagebox.showerror(APP_NAME, error)
            return
        write_profile(values)
        self._set_status(f"Saved {CONFIG_PATH}")

    def on_save_restart(self) -> None:
        self.on_save()
        self.run_service_command("restart")

    def run_service_command(self, command: str) -> None:
        try:
            completed = subprocess.run(
                ["systemctl", "--user", command, SERVICE_NAME],
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
        except FileNotFoundError:
            messagebox.showerror(APP_NAME, "systemctl was not found.")
            return
        output = (completed.stdout or "") + (completed.stderr or "")
        if completed.returncode == 0:
            self._set_status(f"systemctl --user {command} {SERVICE_NAME}: ok")
        else:
            self._set_status(output.strip() or f"systemctl returned {completed.returncode}")
            messagebox.showerror(APP_NAME, output.strip() or f"systemctl returned {completed.returncode}")
        self.refresh_service_status()

    def simulate_gesture(self, gesture: str) -> None:
        values = self.collect_values()
        ok, error = self.validate(values)
        if not ok:
            messagebox.showerror(APP_NAME, error)
            return
        write_profile(values)
        cmd = [
            str(PROJECT_DIR / ".venv" / "bin" / "python"),
            str(PROJECT_DIR / "src" / "magic_mouse_daemon.py"),
            "--profile",
            str(CONFIG_PATH),
            "--simulate",
            gesture,
        ]
        completed = subprocess.run(cmd, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        output = (completed.stdout or "") + (completed.stderr or "")
        if completed.returncode == 0:
            self._set_status(f"Simulated gesture: {gesture}")
        else:
            messagebox.showerror(APP_NAME, output.strip() or f"Simulation failed with rc={completed.returncode}")
            self._set_status(output.strip() or f"Simulation failed with rc={completed.returncode}")

    def refresh_service_status(self) -> None:
        try:
            active = subprocess.run(
                ["systemctl", "--user", "is-active", SERVICE_NAME],
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            enabled = subprocess.run(
                ["systemctl", "--user", "is-enabled", SERVICE_NAME],
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
        except FileNotFoundError:
            self.service_var.set("Service: systemctl not found")
            return

        active_text = (active.stdout or active.stderr).strip() or "unknown"
        enabled_text = (enabled.stdout or enabled.stderr).strip() or "unknown"
        self.service_var.set(f"Service: active={active_text} | enabled={enabled_text}")


def main() -> int:
    root = tk.Tk()
    ControlPanel(root)
    root.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
