#!/usr/bin/env bash
set -euo pipefail

PROJECT_NAME="magic-mouse-linux-gestures"
INSTALL_DIR="$HOME/.local/share/$PROJECT_NAME"
CONFIG_DIR="$HOME/.config/magic-mouse-gestures"
SERVICE_DIR="$HOME/.config/systemd/user"
BIN_DIR="$HOME/.local/bin"
APP_DIR="$HOME/.local/share/applications"
PROFILE="auto"
INSTALL_APT=1
INSTALL_UDEV=0
START_SERVICE=0
HID_PATH=""
BACKEND="auto"

usage() {
  cat <<USAGE
Usage: ./install.sh [--profile cosmic|gnome-ubuntu|auto] [--hid-path /dev/hidrawX] [--backend auto|hidraw|hidapi] [--no-apt] [--udev] [--start]

Options:
  --profile NAME   Desktop profile: cosmic, gnome-ubuntu, or auto. Default: auto.
  --hid-path PATH  Pin a Magic Mouse hidraw path in the installed service profile. Useful for debugging.
  --backend NAME   Input backend: auto, hidraw, or hidapi. Default: auto.
  --no-apt         Do not install apt packages.
  --udev           Install udev rule for hidraw access. Requires sudo.
  --start          Start and enable the user service after install.
  -h, --help       Show this help.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      PROFILE="${2:-}"
      shift 2
      ;;
    --hid-path)
      HID_PATH="${2:-}"
      shift 2
      ;;
    --backend)
      BACKEND="${2:-}"
      shift 2
      ;;
    --no-apt)
      INSTALL_APT=0
      shift
      ;;
    --udev)
      INSTALL_UDEV=1
      shift
      ;;
    --start)
      START_SERVICE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "$PROFILE" == "auto" ]]; then
  desktop="${XDG_CURRENT_DESKTOP:-} ${XDG_SESSION_DESKTOP:-} ${DESKTOP_SESSION:-}"
  desktop="$(echo "$desktop" | tr '[:upper:]' '[:lower:]')"
  if [[ "$desktop" == *"cosmic"* ]]; then
    PROFILE="cosmic"
  elif [[ "$desktop" == *"gnome"* || "$desktop" == *"ubuntu"* ]]; then
    PROFILE="gnome-ubuntu"
  else
    echo "Could not auto-detect desktop profile." >&2
    echo "Run with --profile cosmic or --profile gnome-ubuntu." >&2
    exit 1
  fi
fi

if [[ "$PROFILE" != "cosmic" && "$PROFILE" != "gnome-ubuntu" ]]; then
  echo "Invalid profile: $PROFILE" >&2
  echo "Expected: cosmic, gnome-ubuntu, or auto" >&2
  exit 1
fi

if [[ "$BACKEND" != "auto" && "$BACKEND" != "hidraw" && "$BACKEND" != "hidapi" ]]; then
  echo "Invalid backend: $BACKEND" >&2
  echo "Expected: auto, hidraw, or hidapi" >&2
  exit 1
fi

if [[ ! -f "$SCRIPT_DIR/profiles/$PROFILE.env" ]]; then
  echo "Profile file not found: profiles/$PROFILE.env" >&2
  exit 1
fi

if [[ "$INSTALL_APT" -eq 1 && -x "$(command -v apt-get || true)" ]]; then
  echo "Installing system dependencies with apt..."
  sudo apt-get update
  sudo apt-get install -y python3 python3-venv python3-pip wtype libhidapi-hidraw0 libinput-tools acl
else
  echo "Skipping apt dependency install."
fi

mkdir -p "$INSTALL_DIR" "$CONFIG_DIR" "$SERVICE_DIR" "$BIN_DIR" "$APP_DIR"

# Copy repository files without .git or local venv artifacts.
rm -rf "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
(
  cd "$SCRIPT_DIR"
  tar \
    --exclude='.git' \
    --exclude='.venv' \
    --exclude='__pycache__' \
    -cf - .
) | (cd "$INSTALL_DIR" && tar -xf -)

cp "$SCRIPT_DIR/profiles/$PROFILE.env" "$CONFIG_DIR/profile.env"
{
  echo ""
  echo "# Device/backend overrides generated by install.sh"
  echo "BACKEND="$BACKEND""
  if [[ -n "$HID_PATH" ]]; then
    echo "HID_PATH="$HID_PATH""
  fi
} >> "$CONFIG_DIR/profile.env"
cp "$SCRIPT_DIR/systemd/magic-mouse-gestures.service" "$SERVICE_DIR/magic-mouse-gestures.service"
cp "$SCRIPT_DIR/desktop/magic-mouse-control-panel" "$BIN_DIR/magic-mouse-control-panel"
tmp_desktop="$(mktemp)"
sed "s#__USER__#${USER}#g" "$SCRIPT_DIR/desktop/magic-mouse-control-panel.desktop" > "$tmp_desktop"
cp "$tmp_desktop" "$APP_DIR/magic-mouse-control-panel.desktop"
rm -f "$tmp_desktop"
chmod +x "$BIN_DIR/magic-mouse-control-panel"

python3 -m venv "$INSTALL_DIR/.venv"
"$INSTALL_DIR/.venv/bin/pip" install --upgrade pip
"$INSTALL_DIR/.venv/bin/pip" install -r "$INSTALL_DIR/requirements.txt"

if [[ "$INSTALL_UDEV" -eq 1 ]]; then
  echo "Installing udev rule..."
  sudo groupadd -f magicmouse
  sudo usermod -aG magicmouse "$USER"
  tmp_rule="$(mktemp)"
  sed "s/__MAGIC_MOUSE_USER__/${USER}/g" "$SCRIPT_DIR/udev/99-magic-mouse-gestures.rules" > "$tmp_rule"
  sudo cp "$tmp_rule" /etc/udev/rules.d/99-magic-mouse-gestures.rules
  rm -f "$tmp_rule"
  sudo udevadm control --reload-rules
  sudo udevadm trigger --subsystem-match=hidraw || sudo udevadm trigger
  echo "Applying temporary ACL for currently connected Magic Mouse devices..."
  if [[ -x "$SCRIPT_DIR/scripts/fix-permissions-now.sh" ]]; then
    "$SCRIPT_DIR/scripts/fix-permissions-now.sh" || true
  fi
  echo "Reconnect your Magic Mouse for permanent udev permission changes to apply."
  echo "You were also added to the 'magicmouse' group; log out/in once for the group fallback."
fi

systemctl --user daemon-reload

if [[ "$START_SERVICE" -eq 1 ]]; then
  systemctl --user enable --now magic-mouse-gestures.service
else
  echo "Installed. Start with: systemctl --user start magic-mouse-gestures.service"
  echo "Enable at login with: systemctl --user enable magic-mouse-gestures.service"
fi

echo "Profile installed: $PROFILE"
echo "Backend: $BACKEND"
[[ -n "$HID_PATH" ]] && echo "Pinned HID path: $HID_PATH"
echo "Config: $CONFIG_DIR/profile.env"
echo "Install dir: $INSTALL_DIR"
echo "Control panel launcher: $BIN_DIR/magic-mouse-control-panel"
